name: Go CI/CD

on:

  push:
    branches: [ "main" ]
 
  pull_request:
    branches: [ "main" ]

jobs:
 
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3' 

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          GITHUB_USER: ${{ secrets.GH_USER }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: go test -v ./...